project_id = "milfaoakcaenjsgkdamh"

[functions.public-api-ingest]
verify_jwt = false

[functions.crawler-ingest]
verify_jwt = false

[functions.extract-knx-data]
verify_jwt = false
wall_clock_limit = 300

[functions.extract-knx-objects]
verify_jwt = false
wall_clock_limit = 300